AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for ANMC Documents Metadata'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  ANMCDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'anmc-documents-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ANMC-Digital

Outputs:
  TableName:
    Description: Name of the documents table
    Value: !Ref ANMCDocumentsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the documents table
    Value: !GetAtt ANMCDocumentsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
