AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for ANMC Newsletter Subscribers'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'anmc-subscribers-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CreatedAtIndex
          KeySchema:
            - AttributeName: createdAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ANMC-Digital

Outputs:
  TableName:
    Description: Name of the Subscribers table
    Value: !Ref SubscribersTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the Subscribers table
    Value: !GetAtt SubscribersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
